// Copyright (c) 2016-2026 ReactiveUI and Contributors. All rights reserved.
// ReactiveUI and Contributors licenses this file to you under the MIT license.
// See the LICENSE file in the project root for full license information.

// <auto-generated>

#nullable enable

using System.Runtime.InteropServices;

#if REACTIVELIST_REACTIVE
namespace CrissCross.Reactive.WPF.UI.Interop.WinDef;
#else
namespace CrissCross.WPF.UI.Interop.WinDef;
#endif

/// <summary>The POINT structure defines the x- and y-coordinates of a point.</summary>
[StructLayout(LayoutKind.Sequential)]
public struct POINT
{
    /// <summary>Specifies the x-coordinate of the point.</summary>
    public int x;

    /// <summary>Specifies the y-coordinate of the point.</summary>
    public int y;
}
