// Copyright (c) 2019-2024 ReactiveUI Association Incorporated. All rights reserved.
// ReactiveUI Association Incorporated licenses this file to you under the MIT license.
// See the LICENSE file in the project root for full license information.

// <auto-generated>

#nullable enable

using System.Runtime.InteropServices;

namespace CrissCross.WPF.UI.Interop.WinDef;

/// <summary>
/// The SIZE structure defines the width and height of a rectangle.
/// </summary>
[StructLayout(LayoutKind.Sequential)]
public struct SIZE
{
    /// <summary>
    /// Specifies the rectangle's width. The units depend on which function uses this structure.
    /// </summary>
    public long cx;

    /// <summary>
    /// Specifies the rectangle's height. The units depend on which function uses this structure.
    /// </summary>
    public long cy;
}
