// Copyright (c) 2016-2026 ReactiveUI and Contributors. All rights reserved.
// ReactiveUI and Contributors licenses this file to you under the MIT license.
// See the LICENSE file in the project root for full license information.

namespace CrissCross.WPF.UI.Controls;

/// <summary>PersonPicture Control. Displays the Profile Picture, or in its absence Initials, for a given Contact.</summary>
internal static class InitialsGeneratorExtensions
{
    /// <summary>Maximum leading characters inspected for character type detection.</summary>
    private const int CharacterDetectionLimit = 3;

    /// <summary>Unicode ranges treated as glyph character sets.</summary>
    private static readonly (int Start, int End)[] _glyphRanges =
    [
        (0x0250, 0x02AF),
        (0x0600, 0x06FF),
        (0x0750, 0x077F),
        (0x08A0, 0x08FF),
        (0xFB50, 0xFDFF),
        (0xFE70, 0xFEFF),
        (0x0900, 0x097F),
        (0xA8E0, 0xA8FF),
        (0x0980, 0x09FF),
        (0x0A00, 0x0A7F),
        (0x0A80, 0x0AFF),
        (0x0B00, 0x0B7F),
        (0x0B80, 0x0BFF),
        (0x0C00, 0x0C7F),
        (0x0C80, 0x0CFF),
        (0x0D00, 0x0D7F),
        (0x0D80, 0x0DFF),
        (0x0E00, 0x0E7F),
        (0x0E80, 0x0EFF)
    ];

    /// <summary>Unicode ranges treated as symbolic character sets.</summary>
    private static readonly (int Start, int End)[] _symbolicRanges =
    [
        (0x4E00, 0x9FFF),
        (0x3400, 0x4DBF),
        (0x20000, 0x2A6DF),
        (0x2A700, 0x2B73F),
        (0x2B740, 0x2B81F),
        (0x2E80, 0x2EFF),
        (0x3000, 0x303F),
        (0x31C0, 0x31EF),
        (0x3200, 0x32FF),
        (0x3300, 0x33FF),
        (0xF900, 0xFAFF),
        (0xFE30, 0xFE4F),
        (0x2F800, 0x2FA1F),
        (0x0370, 0x03FF),
        (0x0590, 0x05FF),
        (0x0530, 0x058F)
    ];

    /// <summary>Unicode ranges treated as standard Latin-compatible character sets.</summary>
    private static readonly (int Start, int End)[] _standardRanges =
    [
        (0x0001, 0x007F),
        (0x0080, 0x00FF),
        (0x0100, 0x017F),
        (0x0180, 0x024F),
        (0x2C60, 0x2C7F),
        (0xA720, 0xA7FF),
        (0xAB30, 0xAB6F),
        (0x1E00, 0x1EFF),
        (0x0400, 0x04FF),
        (0x0500, 0x052F),
        (0x0300, 0x036F)
    ];

    /// <summary>Provides extension members.</summary>
    /// <param name="s">The s value.</param>
    extension(string s)
    {
        /// <summary>Provides the SafeSubstring member.</summary>
        /// <param name="startIndex">The startIndex value.</param>
        /// <returns>The result.</returns>
        public string SafeSubstring(int startIndex) =>
            s.SafeSubstring(startIndex, s.Length - startIndex);

        /// <summary>Provides the SafeSubstring member.</summary>
        /// <param name="startIndex">The startIndex value.</param>
        /// <param name="length">The length value.</param>
        /// <returns>The result.</returns>
        public string SafeSubstring(int startIndex, int length)
        {
            if (s is null)
            {
                throw new ArgumentNullException(nameof(s));
            }

            if (startIndex > s.Length)
            {
                return string.Empty;
            }

            if (length > s.Length - startIndex)
            {
                length = s.Length - startIndex;
            }

            return s[startIndex..(startIndex + length)];
        }
    }

    /// <summary>
    /// Helper function which takes a DisplayName, as generated by
    /// Windows.ApplicationModel.Contacts, and returns a initials representation.
    /// </summary>
    /// <param name="contactDisplayName">Display name of the contact.</param>
    /// <returns>
    /// String containing the initials representation of the given DisplayName.
    /// </returns>
    public static string InitialsFromDisplayName(string contactDisplayName)
    {
        var type = GetCharacterType(contactDisplayName);

        // We'll attempt to make initials only if we recognize a name in the Standard character set.
        if (type == CharacterType.Standard)
        {
            var displayName = contactDisplayName;

            StripTrailingBrackets(ref displayName);

            var words = Split(displayName, ' ');

            if (words.Length == 1)
            {
                // If there's only a single long word, we'll show one initial.
                var firstWord = words[0];

                var result = GetFirstFullCharacter(firstWord);

                return result.ToUpper();
            }

            if (words.Length > 1)
            {
                // If there's at least two words, we'll show two initials.
                // NOTE: Based on current implementation, we could be showing punctuation.
                // For example, "John -Smith" would be "J-".
                var firstWord = words[0];
                var lastWord = words[^1];

                var result = GetFirstFullCharacter(firstWord);
                result += GetFirstFullCharacter(lastWord);

                return result.ToUpper();
            }

            // If there's only spaces in the name, we'll get a Vector size of 0.
            return string.Empty;
        }

        // Return empty string. In our code-behind we will produce a generic glyph as a result.
        return string.Empty;
    }

    /// <summary>Helper function which indicates the type of characters in a given string.</summary>
    /// <param name="str">String from which to detect character-set.</param>
    /// <returns>
    /// Character set of the string: Latin, Symbolic, Glyph, or other.
    /// </returns>
    public static CharacterType GetCharacterType(string str)
    {
        // Since we're doing initials, we're really only interested in the first
        // few characters. If the first three characters aren't a glyph then
        // we don't need to count it as such because we won't be changing meaning
        // by truncating to one or two.
        var result = CharacterType.Other;

        for (var i = 0; i < CharacterDetectionLimit; i++)
        {
            // Break on null character. 0xFEFF is a terminating character which appears as null.
            if ((i >= str.Length) || (str[i] == '\0') || (str[i] == 0xFEFF))
            {
                break;
            }

            // In mix-match scenarios, we'll want to follow this order of precedence:
            // Glyph > Symbolic > Roman
            switch (GetCharacterType(str[i]))
            {
                case CharacterType.Glyph:
                    {
                        result = CharacterType.Glyph;
                        break;
                    }

                case CharacterType.Symbolic:
                    {
                        // Don't override a Glyph state with a Symbolic State.
                        if (result != CharacterType.Glyph)
                        {
                            result = CharacterType.Symbolic;
                        }

                        break;
                    }

                case CharacterType.Standard:
                    {
                        // Don't override a Glyph or Symbolic state with a Latin state.
                        if ((result != CharacterType.Glyph) && (result != CharacterType.Symbolic))
                        {
                            result = CharacterType.Standard;
                        }

                        break;
                    }

                case CharacterType.Other:
                    {
                        break;
                    }

                default:
                    {
                        throw new ArgumentOutOfRangeException(nameof(str), str, null);
                    }
            }
        }

        return result;
    }

    /// <summary>Helper function which indicates the character-set of a given character.</summary>
    /// <param name="character">Character for which to detect character-set.</param>
    /// <returns>
    /// Character set of the string: Latin, Symbolic, Glyph, or other.
    /// </returns>
    public static CharacterType GetCharacterType(char character)
    {
        if (IsInAnyRange(character, _glyphRanges))
        {
            return CharacterType.Glyph;
        }

        if (IsInAnyRange(character, _symbolicRanges))
        {
            return CharacterType.Symbolic;
        }

        return IsInAnyRange(character, _standardRanges) ? CharacterType.Standard : CharacterType.Other;
    }

    /// <summary>Helper function which takes in a string and returns a vector of pieces, separated by delimiter.</summary>
    /// <param name="source">String on which to perform the split operation.</param>
    /// <param name="delim">The delimiter.</param>
    /// <param name="maxIterations">Maximum number of times to perform a <c>getline</c> loop.</param>
    /// <returns>
    /// A vector of pieces from the source string, separated by delimiter.
    /// </returns>
    private static string[] Split(string source, char delim, int maxIterations = 25) => source.Split([delim], maxIterations);

    /// <summary>Helper function to remove bracket qualifier from the end of a display name if present.</summary>
    /// <param name="source">String on which to perform the operation.</param>
    private static void StripTrailingBrackets(ref string source)
    {
        // Guidance from the world readiness team is that text within a final set of brackets
        // can be removed for the purposes of calculating initials. ex. John Smith (OSG)
        string[] delimiters = ["{}", "()", "[]"];

        if (source.Length == 0)
        {
            return;
        }

        foreach (var delimiter in delimiters)
        {
            if (source[^1] != delimiter[1])
            {
                continue;
            }

            var start = source.LastIndexOf(delimiter[0]);
            if (start == -1)
            {
                continue;
            }

            source = source.Remove(start);
            return;
        }
    }

    /// <summary>Extracts the first full character from a given string, including any diacritics or combining characters.</summary>
    /// <param name="str">String from which to extract the character.</param>
    /// <returns>A wstring which represents a given character.</returns>
    private static string GetFirstFullCharacter(string str)
    {
        // Index should begin at the first desireable character.
        var start = 0;

        while (start < str.Length)
        {
            var character = str[start];

            if (IsOmittedInitialCharacter(character))
            {
                start++;
                continue;
            }

            break;
        }

        // If no desireable characters exist, we'll start at index 1, as combining
        // characters begin only after the first character.
        if (start >= str.Length)
        {
            start = 0;
        }

        // Combining characters begin only after the first character, so we should start
        // looking 1 after the start character.
        var index = start + 1;

        while (index < str.Length)
        {
            var character = str[index];

            if (!IsCombiningDiacriticalMark(character))
            {
                break;
            }

            index++;
        }

        // Determine number of diacritics by adjusting for our initial offset.
        var strLength = index - start;

        return str.SafeSubstring(start, strLength);
    }

    /// <summary>Determines whether the code point is in one of the supplied ranges.</summary>
    /// <param name="codePoint">The Unicode code point.</param>
    /// <param name="ranges">The ranges to inspect.</param>
    /// <returns><c>true</c> when the code point is in a range; otherwise, <c>false</c>.</returns>
    private static bool IsInAnyRange(int codePoint, (int Start, int End)[] ranges) =>
        ranges.Any(range => codePoint >= range.Start && codePoint <= range.End);

    /// <summary>Determines whether the character is a combining diacritical mark.</summary>
    /// <param name="character">The character to inspect.</param>
    /// <returns><c>true</c> for combining diacritical marks; otherwise, <c>false</c>.</returns>
    private static bool IsCombiningDiacriticalMark(char character) =>
        character is >= (char)0x0300 and <= (char)0x036F;

    /// <summary>Determines whether the character should be skipped at the beginning of initials.</summary>
    /// <param name="character">The character to inspect.</param>
    /// <returns><c>true</c> when the character should be omitted; otherwise, <c>false</c>.</returns>
    private static bool IsOmittedInitialCharacter(char character) =>
        character is
            (>= (char)0x0021 and <= (char)0x002F) or
            (>= (char)0x003A and <= (char)0x0040) or
            (>= (char)0x007B and <= (char)0x007E);
}
