// Copyright (c) Chris Pulman. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

// <auto-generated>
//   This file has been borrowed from Wpf-UI.
// </auto-generated>

#nullable enable

// This Source Code Form is subject to the terms of the MIT License.
// If a copy of the MIT was not distributed with this file, You can obtain one at https://opensource.org/licenses/MIT.
// Copyright (C) Leszek Pomianowski and WPF UI Contributors.
// All Rights Reserved.

// ReSharper disable once CheckNamespace
namespace CrissCross.WPF.UI.Controls;

/// <summary>
/// Defines constants that specify the default button on a <see cref="MessageBox"/>.
/// </summary>
public enum MessageBoxButton
{
    /// <summary>
    /// The primary button
    /// </summary>
    Primary,

    /// <summary>
    /// The secondary button
    /// </summary>
    Secondary,

    /// <summary>
    /// The close button
    /// </summary>
    Close
}
