// Copyright (c) Chris Pulman. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

// <auto-generated>
//   This file has been borrowed from Wpf-UI.
// </auto-generated>

#nullable enable

// This Source Code Form is subject to the terms of the MIT License.
// If a copy of the MIT was not distributed with this file, You can obtain one at https://opensource.org/licenses/MIT.
// Copyright (C) Leszek Pomianowski and WPF UI Contributors.
// All Rights Reserved.

namespace CrissCross.WPF.UI.Controls;

/// <summary>
/// Defines several predefined text styles that you can apply to some elements responsible for displaying it.
/// <para><see href="https://learn.microsoft.com/en-us/windows/apps/design/style/typography"/></para>
/// </summary>
public enum FontTypography
{
    Caption,
    Body,
    BodyStrong,
    Subtitle,
    Title,
    TitleLarge,
    Display
}
