// Copyright (c) 2019-2024 ReactiveUI Association Incorporated. All rights reserved.
// ReactiveUI Association Incorporated licenses this file to you under the MIT license.
// See the LICENSE file in the project root for full license information.

// <auto-generated>

#nullable enable

namespace CrissCross.WPF.UI.Interop;

/// <summary>
/// Windows kernel module.
/// </summary>
internal static class Libraries
{
    internal const string Dwmapi = "dwmapi.dll";
    internal const string Kernel32 = "kernel32.dll";
    internal const string Shell32 = "shell32.dll";
    internal const string User32 = "user32.dll";
    internal const string UxTheme = "uxtheme.dll";
    internal const string Version = "version.dll";
}
