// Copyright (c) 2016-2026 ReactiveUI and Contributors. All rights reserved.
// ReactiveUI and Contributors licenses this file to you under the MIT license.
// See the LICENSE file in the project root for full license information.

// <auto-generated>

#nullable enable

#if REACTIVELIST_REACTIVE
namespace CrissCross.Reactive.WPF.UI.Interop;
#else
namespace CrissCross.WPF.UI.Interop;
#endif

/// <summary>Windows kernel module.</summary>
internal static class Libraries
{
    internal const string Dwmapi = "dwmapi.dll";
    internal const string Kernel32 = "kernel32.dll";
    internal const string Shell32 = "shell32.dll";
    internal const string User32 = "user32.dll";
    internal const string UxTheme = "uxtheme.dll";
    internal const string Version = "version.dll";
}
